
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author roberto
 */
public class Urna extends javax.swing.JFrame {

    public int contador = 0;
    String temp;

    /**
     * Creates new form Urna
     */
    public Urna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmdAjuda = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPriNum = new javax.swing.JLabel();
        lblSegNum = new javax.swing.JLabel();
        lblTerNum = new javax.swing.JLabel();
        lblQuaNum = new javax.swing.JLabel();
        lblQuiNum = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblSeuVotoPara = new javax.swing.JLabel();
        lblNúmero = new javax.swing.JLabel();
        lblPartido = new javax.swing.JLabel();
        lblCampPartido = new javax.swing.JLabel();
        cmdAdmin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmdUm = new javax.swing.JButton();
        cmdConfirma = new javax.swing.JButton();
        cmdCorrige = new javax.swing.JButton();
        cmdBranco = new javax.swing.JButton();
        cmdDois = new javax.swing.JButton();
        cmdTres = new javax.swing.JButton();
        cmdQuatro = new javax.swing.JButton();
        cmdCinco = new javax.swing.JButton();
        cmdSeis = new javax.swing.JButton();
        cmdSete = new javax.swing.JButton();
        cmdOito = new javax.swing.JButton();
        cmdNove = new javax.swing.JButton();
        cmdZero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmdAjuda.setText("Ajuda");
        cmdAjuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAjudaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_1.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPriNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPriNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblSegNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSegNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSegNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        lblSegNum.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lblSegNumComponentAdded(evt);
            }
        });
        lblSegNum.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblSegNumPropertyChange(evt);
            }
        });

        lblTerNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTerNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTerNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblQuaNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuaNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuaNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblQuiNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuiNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuiNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblCargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCargo.setText(" Vereador");

        lblSeuVotoPara.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeuVotoPara.setText("SEU VOTO PARA");

        lblNúmero.setText("Número:");

        lblPartido.setText("Partido:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblNúmero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPriNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lblSegNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lblTerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lblQuaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lblQuiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeuVotoPara))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPartido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCampPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeuVotoPara)
                .addGap(30, 30, 30)
                .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSegNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPriNum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblNúmero)))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartido)
                    .addComponent(lblCampPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        cmdAdmin.setText("Admin");
        cmdAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdAdmin.setMaximumSize(new java.awt.Dimension(33, 25));
        cmdAdmin.setMinimumSize(new java.awt.Dimension(33, 25));
        cmdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdminActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        cmdUm.setBackground(new java.awt.Color(0, 0, 0));
        cmdUm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdUm.setForeground(new java.awt.Color(255, 255, 255));
        cmdUm.setText("1");
        cmdUm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdUm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdUm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUmActionPerformed(evt);
            }
        });

        cmdConfirma.setBackground(new java.awt.Color(0, 153, 0));
        cmdConfirma.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        cmdConfirma.setText("CONFIRMA");
        cmdConfirma.setActionCommand("CONFIRM");
        cmdConfirma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdConfirma.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfirmaActionPerformed(evt);
            }
        });

        cmdCorrige.setBackground(new java.awt.Color(204, 51, 0));
        cmdCorrige.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        cmdCorrige.setText("CORRIGE");
        cmdCorrige.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 0, 0), null, null));
        cmdCorrige.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdCorrige.setPreferredSize(new java.awt.Dimension(39, 33));
        cmdCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCorrigeActionPerformed(evt);
            }
        });

        cmdBranco.setBackground(new java.awt.Color(255, 255, 255));
        cmdBranco.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        cmdBranco.setText("BRANCO");
        cmdBranco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdBranco.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdBranco.setPreferredSize(new java.awt.Dimension(39, 33));

        cmdDois.setBackground(new java.awt.Color(0, 0, 0));
        cmdDois.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdDois.setForeground(new java.awt.Color(255, 255, 255));
        cmdDois.setText("2");
        cmdDois.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdDois.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdDois.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDoisActionPerformed(evt);
            }
        });

        cmdTres.setBackground(new java.awt.Color(0, 0, 0));
        cmdTres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdTres.setForeground(new java.awt.Color(255, 255, 255));
        cmdTres.setText("3");
        cmdTres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdTres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdTres.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTresActionPerformed(evt);
            }
        });

        cmdQuatro.setBackground(new java.awt.Color(0, 0, 0));
        cmdQuatro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdQuatro.setForeground(new java.awt.Color(255, 255, 255));
        cmdQuatro.setText("4");
        cmdQuatro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdQuatro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdQuatro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuatroActionPerformed(evt);
            }
        });

        cmdCinco.setBackground(new java.awt.Color(0, 0, 0));
        cmdCinco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdCinco.setForeground(new java.awt.Color(255, 255, 255));
        cmdCinco.setText("5");
        cmdCinco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCinco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdCinco.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCincoActionPerformed(evt);
            }
        });

        cmdSeis.setBackground(new java.awt.Color(0, 0, 0));
        cmdSeis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdSeis.setForeground(new java.awt.Color(255, 255, 255));
        cmdSeis.setText("6");
        cmdSeis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdSeis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdSeis.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeisActionPerformed(evt);
            }
        });

        cmdSete.setBackground(new java.awt.Color(0, 0, 0));
        cmdSete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdSete.setForeground(new java.awt.Color(255, 255, 255));
        cmdSete.setText("7");
        cmdSete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdSete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdSete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeteActionPerformed(evt);
            }
        });

        cmdOito.setBackground(new java.awt.Color(0, 0, 0));
        cmdOito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdOito.setForeground(new java.awt.Color(255, 255, 255));
        cmdOito.setText("8");
        cmdOito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdOito.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdOito.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOitoActionPerformed(evt);
            }
        });

        cmdNove.setBackground(new java.awt.Color(0, 0, 0));
        cmdNove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdNove.setForeground(new java.awt.Color(255, 255, 255));
        cmdNove.setText("9");
        cmdNove.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdNove.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdNove.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNoveActionPerformed(evt);
            }
        });

        cmdZero.setBackground(new java.awt.Color(0, 0, 0));
        cmdZero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdZero.setForeground(new java.awt.Color(255, 255, 255));
        cmdZero.setText("0");
        cmdZero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdZero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cmdZero.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cmdZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdZeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdDois, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdCinco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmdZero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdOito, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmdUm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdSete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmdBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(cmdCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdNove, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdTres, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdUm, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdTres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDois, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdNove, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdOito, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdZero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdConfirma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(cmdAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(478, 478, 478))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCincoActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("5");
                contador++;
                break;
            case 1:
                lblSegNum.setText("5");
                contador++;
                break;
            case 2:
                lblTerNum.setText("5");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("5");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("5");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCincoActionPerformed

    private void cmdConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfirmaActionPerformed
        if (contador >= 5) {
            int numCand = Integer.parseInt(lblTerNum.getText() + lblQuaNum.getText() + lblQuiNum.getText());
            Candidato candidato = CandidatoRepo.getCandidato(numCand); 
       candidato.addVoto();
       lblPriNum.setText("");
       lblSegNum.setText("");
       lblTerNum.setText("");
       lblQuaNum.setText("");
       lblQuiNum.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        
    }//GEN-LAST:event_cmdConfirmaActionPerformed

    private void cmdUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUmActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("1");
                contador++;
                break;
            case 1:
                lblSegNum.setText("1");
                contador++;
                break;
            case 2:
                lblTerNum.setText("1");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("1");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("1");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }     // TODO add your handling code here:
    }//GEN-LAST:event_cmdUmActionPerformed

    private void cmdDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDoisActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("2");
                contador++;
                break;
            case 1:
                lblSegNum.setText("2");
                contador++;
                break;
            case 2:
                lblTerNum.setText("2");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("2");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("2");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;

        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdDoisActionPerformed

    private void cmdTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTresActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("3");
                contador++;
                break;
            case 1:
                lblSegNum.setText("3");
                contador++;
                break;
            case 2:
                lblTerNum.setText("3");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("3");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("3");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdTresActionPerformed

    private void cmdQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuatroActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("4");
                contador++;
                break;
            case 1:
                lblSegNum.setText("4");
                contador++;
                break;
            case 2:
                lblTerNum.setText("4");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("4");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("4");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdQuatroActionPerformed

    private void cmdSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeisActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("6");
                contador++;
                break;
            case 1:
                lblSegNum.setText("6");
                contador++;
                break;
            case 2:
                lblTerNum.setText("6");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("6");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("6");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSeisActionPerformed

    private void cmdSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeteActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("7");
                contador++;
                break;
            case 1:
                lblSegNum.setText("7");
                contador++;
                break;
            case 2:
                lblTerNum.setText("7");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("7");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("7");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdSeteActionPerformed

    private void cmdOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOitoActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("8");
                contador++;
                break;
            case 1:
                lblSegNum.setText("8");
                contador++;
                break;
            case 2:
                lblTerNum.setText("8");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("8");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("8");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdOitoActionPerformed

    private void cmdNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNoveActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("9");
                contador++;
                break;
            case 1:
                lblSegNum.setText("9");
                contador++;
                break;
            case 2:
                lblTerNum.setText("9");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("9");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("9");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdNoveActionPerformed

    private void cmdZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdZeroActionPerformed
        switch (contador) {
            case 0:
                lblPriNum.setText("0");
                contador++;
                break;
            case 1:
                lblSegNum.setText("0");
                contador++;
                break;
            case 2:
                lblTerNum.setText("0");
                contador++;
                break;
            case 3:
                lblQuaNum.setText("0");
                contador++;
                break;
            case 4:
                lblQuiNum.setText("0");
                contador++;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Não há mais campos!");
                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmdZeroActionPerformed

    private void cmdCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCorrigeActionPerformed
        if (contador == 0) {
            System.exit(0);
        }
        lblPriNum.setText(null);
        lblSegNum.setText(null);        // TODO add your handling code here:
        lblTerNum.setText(null);        // TODO add your handling code here:
        lblQuaNum.setText(null);        // TODO add your handling code here:
        lblQuiNum.setText(null);
        lblPartido.setVisible(false);
        lblCampPartido.setText(null);
        contador = 0;
    }//GEN-LAST:event_cmdCorrigeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblPartido.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void lblSegNumComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lblSegNumComponentAdded


    }//GEN-LAST:event_lblSegNumComponentAdded

    private void lblSegNumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblSegNumPropertyChange
        if (contador == 1) {
            lblPartido.setVisible(true);
            int conver = Integer.parseInt(lblPriNum.getText() + "" + lblSegNum.getText());
            switch (conver) {
                case 21:
                    lblCampPartido.setText("Ao Meio");
                    break;
                case 91:
                    lblCampPartido.setText("Em Pedaços");
                    break;
                case 12:
                    lblCampPartido.setText("Pode Ser");
                    break;
                default:
                    contador = -1;
                    lblCampPartido.setText(null);
                    lblPriNum.setText(null);
                    lblSegNum.setText(null);
                    lblPartido.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Partido inválido!");
            }
        }
    }//GEN-LAST:event_lblSegNumPropertyChange

    private void cmdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdminActionPerformed
        Admin novo = new Admin();
        novo.show();// TODO add your handling code here:
    }//GEN-LAST:event_cmdAdminActionPerformed

    private void cmdAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAjudaActionPerformed
        Ajuda novo = new Ajuda();
        novo.show();      // TODO add your handling code here:
    }//GEN-LAST:event_cmdAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdmin;
    private javax.swing.JButton cmdAjuda;
    private javax.swing.JButton cmdBranco;
    private javax.swing.JButton cmdCinco;
    private javax.swing.JButton cmdConfirma;
    private javax.swing.JButton cmdCorrige;
    private javax.swing.JButton cmdDois;
    private javax.swing.JButton cmdNove;
    private javax.swing.JButton cmdOito;
    private javax.swing.JButton cmdQuatro;
    private javax.swing.JButton cmdSeis;
    private javax.swing.JButton cmdSete;
    private javax.swing.JButton cmdTres;
    private javax.swing.JButton cmdUm;
    private javax.swing.JButton cmdZero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCampPartido;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNúmero;
    private javax.swing.JLabel lblPartido;
    private javax.swing.JLabel lblPriNum;
    private javax.swing.JLabel lblQuaNum;
    private javax.swing.JLabel lblQuiNum;
    private javax.swing.JLabel lblSegNum;
    private javax.swing.JLabel lblSeuVotoPara;
    private javax.swing.JLabel lblTerNum;
    // End of variables declaration//GEN-END:variables
}
